
		USE Stomp_test;



		DELETE FROM Transaction;
		DELETE FROM Material;
		DELETE FROM Stomper_Team;
		DELETE FROM Team;
		DELETE FROM Class;
		DELETE FROM Stomper WHERE uid > 2;
		DELETE FROM Teacher;
		DELETE FROM School;

ALTER TABLE School AUTO_INCREMENT = 1;
CALL newSchool('Argenziano','290 Washington St','Somerville',02143,6176295465);
CALL newSchool('Benjamin Brown','201 Willow Ave','Somerville',02144,6176295620);
CALL newSchool('Brooks','388 High St','Medford',02155,7813932166);
CALL newSchool('Columbus','37 Hicks Ave','Medford',02155,7813932177);
CALL newSchool('East Somerville','50 Cross St','Somerville',02145,6176295400);
CALL newSchool('Healey','5 Meacham St','Somerville',02145,6176295420);
CALL newSchool('International School of Boston','45 Matignon Rd','Cambridge',02140,6174991451);
CALL newSchool('JQS','885 Washington St','Boston',02111,6176358497);
CALL newSchool('Linden STEAM','29 Wescott St','Malden',02148,7813977329);
CALL newSchool('Parlin School','587 Broadway','Everet',02149,6173942480);
CALL newSchool('St. Joseph's','132 High St','Medford',02155,7813963636);
CALL newSchool('Stratton','180 Mountain Ave','Arlington',02474,7813163754);
CALL newSchool('Vinson Owen','75 Johnson Rd','Winchester',01890,7817217019);
CALL newSchool('West Somerville','177 Powder House Blvd','Somerville',02144,6176256600);


ALTER TABLE Teacher AUTO_INCREMENT = 1;
CALL newTeacher('Carol','Murphy','camurphy@k12.somerville.ma.us','Argenziano');
CALL newTeacher('Carol','Murphy','_camurphy@k12.somerville.ma.us','Argenziano');
CALL newTeacher('Julia','Jasper','jjasper@k12.somerville.ma.us;amyroschelle@gmail.com','Benjamin Brown');
CALL newTeacher('Anna','McCormick','anna.t.mccormick@gmail.com','Brooks');
CALL newTeacher('Megan','Gover','mgover@medford.k12.ma.us','Brooks');
CALL newTeacher('Abby','Herman','aherman@medford.k12.ma.us','Brooks');
CALL newTeacher('Sharon','Baxter','sbaxter@medford.k12.ma.us','Brooks');
CALL newTeacher('Jennifer','Conti','jconti@medford.k12.ma.us','Brooks');
CALL newTeacher('Laura','Vincent','lvincent@medford.k12.ma.us','Columbus');
CALL newTeacher('Becky','Cogbill','rcogbill@medford.k12.ma.us','Columbus');
CALL newTeacher('Emma','Mrozicki','emrozicki@k12.somerville.ma.us','East Somerville');
CALL newTeacher('Claire','Sheehan','Claire.sheehan92@gmail.com','Healey');
CALL newTeacher('Ben','Garton','bgarton@k12.somerville.ma.us','Healey');
CALL newTeacher('Sara','Bassett','sbassett@k12.somerville.ma.us','Healey');
CALL newTeacher('J','Hermann','jhermann@k12.somerville.ma.us','Healey');
CALL newTeacher('Alexandra','Sweder','acorsaro@k12.somerville.ma.us','Healey');
CALL newTeacher('Lizzy','Mayer','emayer@isbos.org','International School of Boston');
CALL newTeacher('Matt','Lydon','mattmlydon@gmail.com','JQS');
CALL newTeacher('Kelly','Keefe','kellylkeefe@gmail.com','JQS');
CALL newTeacher('Mimi','Fong','msfongquincy@gmail.com','JQS');
CALL newTeacher('Cindy','Shum','clau3@bostonpublicschools.org','JQS');
CALL newTeacher('Lisa','Hanifan','lhanifan@maldenps.org','Linden STEAM');
CALL newTeacher('Ilene','Timmons','itimmons@maldenps.org','Linden STEAM');
CALL newTeacher('Meredith','Nichols','mnichols@maldenps.org','Linden STEAM');
CALL newTeacher('Keri','Gangemi','kgangemi@maldenps.org','Linden STEAM');
CALL newTeacher('Mary Jane','McDonagh','mmcdonough@maldenps.org','Linden STEAM');
CALL newTeacher('Katelyn','Crossly','kdondero@everett.k12.ma.us','Parlin School');
CALL newTeacher('Lauren','Fiore','lillauren0766@yahoo.com','St. Joseph's');
CALL newTeacher('Christine','Whitney','cwhitney@stjosephschoolmedford.com','St. Joseph's');
CALL newTeacher('Amber','Bus','abus@arlington.k12.ma.us','Stratton');
CALL newTeacher('Janelle','Ricciuti','jricciuti@arlington.k12.ma.us','Stratton');
CALL newTeacher('Carolyn','Snook','csnook@arlington.k12.ma.us','Stratton');
CALL newTeacher('Jill','Pappas','jpappas@winchesterps.org','Vinson Owen');
CALL newTeacher('Elaine','Bowler','ebowler@winchesterps.org','Vinson Owen');
CALL newTeacher('Megan','Simmons','msimmons@winchesterps.org','Vinson Owen');
CALL newTeacher('Maggie','Jackson','mjackson@winchesterps.org','Vinson Owen');
CALL newTeacher('Sophia','Carafotes','scarafotes@k12.somerville.ma.us','West Somerville');
CALL newTeacher('Lorin','Desrochers','ldesrochers@k12.somerville.ma.us','West Somerville');
CALL newTeacher('Charlene','Buckley','Cbuckley@k12.somerville.ma.us','West Somerville');
CALL newTeacher('Danielle','Shulman','dshulman@k12.somerville.ma.us','West Somerville');


ALTER TABLE Stomper AUTO_INCREMENT = 2;
CALL newStomper('Brian','Bertini','brian.bertini@gmail.com','bberti02', 'stomp','Stomper');
CALL newStomper('Shanon','Geary','Shannon.Geary@tufts.edu','sgeary03', 'stomp','Stomper');
CALL newStomper('Avni','Rajpal','avni.rajpal@tufts.edu','arajpa01', 'stomp','Stomper');
CALL newStomper('Tessa','Garces','tessagarces@gmail.com','tgarce01', 'stomp','Stomper');
CALL newStomper('Katherine ','McMurray','kmcmurray7895@gmail.com','kmcmur01', 'stomp','Stomper');
CALL newStomper('Declan','Devine','declandevine1@gmail.com','ddevin01', 'stomp','Stomper');
CALL newStomper('Chris ','Keyes','christopher.keyes@tufts.edu','ckeyes03', 'stomp','Stomper');
CALL newStomper('Camille','Carlisle','camille.carlisle@tufts.edu','ccarli01', 'stomp','Stomper');
CALL newStomper('Winnie','Lin','winnie1419@gmail.com','wlin01', 'stomp','Stomper');
CALL newStomper('Iris','Oliver','iris.oliver@tufts.edu','iolive01', 'stomp','Stomper');
CALL newStomper('Ryan','Eccleston-Murdock','Ryan.Eccleston_Murdock@tufts.edu','reccle01', 'stomp','Stomper');
CALL newStomper('Caroline','Passalacqua','caroline.passalacqua@tufts.edu','cpassa01', 'stomp','Stomper');
CALL newStomper('Jessie','Duggan','jduggan22@yahoo.com','jdugga03', 'stomp','Stomper');
CALL newStomper('Kristina','Chu','Kristina.Chu@tufts.edu','kchu04', 'stomp','Stomper');
CALL newStomper('Christopher','Camacho','christopher.camacho@tufts.edu','ccamac01', 'stomp','Stomper');
CALL newStomper('Camille','Mbayo','Camille-Louise.Mbayo@tufts.edu','cmbayo01', 'stomp','Stomper');
CALL newStomper('Kirsten','Jorgensen','kirsten.jorgensen@tufts.edu','kjorge01', 'stomp','Stomper');
CALL newStomper('John','Fernandez','Fernandezljohn@gmail.com','jferna07', 'stomp','Stomper');
CALL newStomper('Raul','Gomez','raul.gomez@tufts.edu','rgomez01', 'stomp','Stomper');
CALL newStomper('Eva','Philips','Eva.Philips@tufts.edu','ephili02', 'stomp','Stomper');
CALL newStomper('Tommy','George','thomas.george@tufts.edu','tgeorg03', 'stomp','Stomper');
CALL newStomper('Elizabeth','Moison','Elizabeth.moison@tufts.edu','emoiso01', 'stomp','Stomper');
CALL newStomper('Mile','Krstev','mile.krstev@tufts.edu','mkrste01', 'stomp','Stomper');
CALL newStomper('Jesus','Garcia','Jesus.Garcia@tufts.edu','jgarci11', 'stomp','Stomper');
CALL newStomper('Elizabeth','dossett','elizabeth.dossett@tufts.edu','edosse01', 'stomp','Stomper');
CALL newStomper('Jhanel','Chew','jhanel.chew@tufts.edu','jchew01', 'stomp','Stomper');
CALL newStomper('Heresa','Laforce','heresa.laforce@tufts.edu','hlafor03', 'stomp','Stomper');
CALL newStomper('Alexandra','Webster','alexandra.webster@tufts.edu','awebst02', 'stomp','Stomper');
CALL newStomper('Orian','Sneor','orian.sneor@tufts.edu','osneor01', 'stomp','Stomper');
CALL newStomper('Daniel','McKeen','drmckeen@mckhome.net','dmckee01', 'stomp','Stomper');
CALL newStomper('Rachel','Kramer','Rachel.Kramer@tufts.edu','rkrame02', 'stomp','Stomper');
CALL newStomper('Annie','Geheran','anne.geheran@tufts.edu','ageher01', 'stomp','Stomper');
CALL newStomper('Jared','Sawyer','jaredliam7@gmail.com','jsawye01', 'stomp','Stomper');
CALL newStomper('Clara','Oppenheimer','clara.oppenheimer@tufts.edu','coppen02', 'stomp','Stomper');
CALL newStomper('Camila','Menard','camila.menard@tufts.edu','cmenar01', 'stomp','Stomper');
CALL newStomper('Justin','Reyes','Justin.Reyes@tufts.edu','jreyes08', 'stomp','Stomper');
CALL newStomper('Sara','pearce-probst','sara.pearce_probst@tufts.edu','spearc01', 'stomp','Stomper');
CALL newStomper('Daniel','Weinstein','d.weinstein219@gmail.com','dweins01', 'stomp','Stomper');
CALL newStomper('Ross','Kamen','ross.kamen@tufts.edu','rkamen02', 'stomp','Stomper');
CALL newStomper('Rati','Srinivasan','rati.srinivasan7@gmail.com','rsrini02', 'stomp','Stomper');
CALL newStomper('Becca','Larson','rebecca.larson@tufts.edu','rlarso02', 'stomp','Stomper');
CALL newStomper('Kevin','Dunn','kevin_j.dunn@tufts.edu','kdunn06', 'stomp','Stomper');
CALL newStomper('Erynne','van Zee','erynne11@gmail.com','evanze01', 'stomp','Stomper');
CALL newStomper('Kanav','Jhunjhunwala','kanav.jhunjhunwala@tufts.edu','kjhunj01', 'stomp','Stomper');
CALL newStomper('Emma','Coltoff','emma.coltoff@tufts.edu','ecolto01', 'stomp','Stomper');
CALL newStomper('Erica','Albert','erica.albert@tufts.edu','ealber01', 'stomp','Stomper');
CALL newStomper('Emma','Cusack','emma.cusack@tufts.edu','ecusac01', 'stomp','Stomper');
CALL newStomper('Sanya','Pradhan','sanyapradhan28@gmail.com','spradh05', 'stomp','Stomper');
CALL newStomper('Caitlin','Duffy','Caitlin.duffy@tufts.edu','cduffy01', 'stomp','Stomper');
CALL newStomper('Amal','Omar','amal.omar@tufts.edu','aomar02', 'stomp','Stomper');
CALL newStomper('Liren','Fu','liren.fu@tufts.edu','lfu01', 'stomp','Stomper');
CALL newStomper('Eddie','Futterman','edward.futterman@tufts.edu','efutte01', 'stomp','Stomper');
CALL newStomper('Alex','Klein','alexander.klein@tufts.edu','aklein08', 'stomp','Stomper');
CALL newStomper('Simone','Draper','simone.draper@tufts.edu','sdrape01', 'stomp','Stomper');
CALL newStomper('Clara','Eshaghpour','clara.eshaghpour@tufts.edu','ceshag01', 'stomp','Stomper');
CALL newStomper('Isaac','Collins','Isaac.Collins@tufts.edu','icolli01', 'stomp','Stomper');
CALL newStomper('','','','', 'stomp','');


ALTER TABLE Class AUTO_INCREMENT = 1;
ALTER TABLE Team AUTO_INCREMENT = 1;
ALTER TABLE Stomper_Team AUTO_INCREMENT = 2;
CALL newClass('anna.t.mccormick@gmail.com','10:15-11:40','Friday',4);
CALL newTeam('anna.t.mccormick@gmail.com','Friday');
CALL newStomperTeam('Brian', 'Bertini', 'anna.t.mccormick@gmail.com','Friday');
CALL newStomperTeam('Shanon', 'Rose', 'anna.t.mccormick@gmail.com','Friday');
CALL newClass('aherman@medford.k12.ma.us','10:15-11:40','Friday',4);
CALL newTeam('aherman@medford.k12.ma.us','Friday');
CALL newStomperTeam('Avni', 'Rajpal', 'aherman@medford.k12.ma.us','Friday');
CALL newStomperTeam('Tessa', 'Garces', 'aherman@medford.k12.ma.us','Friday');
CALL newClass('emrozicki@k12.somerville.ma.us','11:00-1:00','Friday',4);
CALL newTeam('emrozicki@k12.somerville.ma.us','Friday');
CALL newStomperTeam('Katherine', 'McMurray', 'emrozicki@k12.somerville.ma.us','Friday');
CALL newStomperTeam('Declan', 'Devine', 'emrozicki@k12.somerville.ma.us','Friday');
CALL newClass('Claire.sheehan92@gmail.com','12:30-2:30','Friday',4);
CALL newTeam('Claire.sheehan92@gmail.com','Friday');
CALL newStomperTeam('Chris', 'Keyes', 'Claire.sheehan92@gmail.com','Friday');
CALL newStomperTeam('Camille', 'Carlisle', 'Claire.sheehan92@gmail.com','Friday');
CALL newClass('sbassett@k12.somerville.ma.us','12:30-2:30','Friday',4);
CALL newTeam('sbassett@k12.somerville.ma.us','Friday');
CALL newStomperTeam('Winnie', 'Lin', 'sbassett@k12.somerville.ma.us','Friday');
CALL newStomperTeam('Iris', 'Oliver', 'sbassett@k12.somerville.ma.us','Friday');
CALL newClass('mattmlydon@gmail.com','11:30-1:30','Friday',5);
CALL newTeam('mattmlydon@gmail.com','Friday');
CALL newStomperTeam('Ryan', 'Eccleston-Murdock', 'mattmlydon@gmail.com','Friday');
CALL newStomperTeam('Caroline', 'Passalacqua', 'mattmlydon@gmail.com','Friday');
CALL newClass('abus@arlington.k12.ma.us','8:10-10:00','Friday',5);
CALL newTeam('abus@arlington.k12.ma.us','Friday');
CALL newStomperTeam('Jessie', 'Duggan', 'abus@arlington.k12.ma.us','Friday');
CALL newStomperTeam('Kristina', 'Chu', 'abus@arlington.k12.ma.us','Friday');
CALL newClass('jpappas@winchesterps.org','1:15-2:15','Friday',5);
CALL newTeam('jpappas@winchesterps.org','Friday');
CALL newStomperTeam('Christopher', 'Camacho', 'jpappas@winchesterps.org','Friday');
CALL newStomperTeam('Camille', 'Mbayo', 'jpappas@winchesterps.org','Friday');
CALL newClass('ebowler@winchesterps.org','1:15-2:15','Friday',4);
CALL newTeam('ebowler@winchesterps.org','Friday');
CALL newStomperTeam('Kirsten', 'Jorgensen', 'ebowler@winchesterps.org','Friday');
CALL newStomperTeam('John', 'Fernandez', 'ebowler@winchesterps.org','Friday');
CALL newClass('msimmons@winchesterps.org','1:15-2:15','Friday',5);
CALL newTeam('msimmons@winchesterps.org','Friday');
CALL newStomperTeam('Raul', 'Gomez', 'msimmons@winchesterps.org','Friday');
CALL newStomperTeam('Eva', 'Philips', 'msimmons@winchesterps.org','Friday');
CALL newClass('scarafotes@k12.somerville.ma.us','11:30-1:00','Friday',3);
CALL newTeam('scarafotes@k12.somerville.ma.us','Friday');
CALL newStomperTeam('Tommy', 'George', 'scarafotes@k12.somerville.ma.us','Friday');
CALL newStomperTeam('Elizabeth', 'Moison', 'scarafotes@k12.somerville.ma.us','Friday');
CALL newClass('msfongquincy@gmail.com','12:40-2:40','Monday',5);
CALL newTeam('msfongquincy@gmail.com','Monday');
CALL newStomperTeam('Mile', 'Krstev', 'msfongquincy@gmail.com','Monday');
CALL newStomperTeam('Jesus', 'Garcia', 'msfongquincy@gmail.com','Monday');
CALL newClass('camurphy@k12.somerville.ma.us','8:30-9:30','Monday',5);
CALL newTeam('camurphy@k12.somerville.ma.us','Monday');
CALL newStomperTeam('Elizabeth', 'dossett', 'camurphy@k12.somerville.ma.us','Monday');
CALL newStomperTeam('Jhanel', 'Chew', 'camurphy@k12.somerville.ma.us','Monday');
CALL newClass('_camurphy@k12.somerville.ma.us','10:30-11:30','Monday',5);
CALL newTeam('_camurphy@k12.somerville.ma.us','Monday');
CALL newStomperTeam('Alexandra', 'Webster', '_camurphy@k12.somerville.ma.us','Monday');
CALL newStomperTeam('Heresa', 'Laforce', '_camurphy@k12.somerville.ma.us','Monday');
CALL newClass('lvincent@medford.k12.ma.us','12:30-2:25','Monday',4);
CALL newTeam('lvincent@medford.k12.ma.us','Monday');
CALL newStomperTeam('Orian', 'Sneor', 'lvincent@medford.k12.ma.us','Monday');
CALL newStomperTeam('Daniel', 'McKeen', 'lvincent@medford.k12.ma.us','Monday');
CALL newClass('Cbuckley@k12.somerville.ma.us','10-11:30','Monday',4);
CALL newTeam('Cbuckley@k12.somerville.ma.us','Monday');
CALL newStomperTeam('Rachel', 'Kramer', 'Cbuckley@k12.somerville.ma.us','Monday');
CALL newStomperTeam('Annie', 'Geheran', 'Cbuckley@k12.somerville.ma.us','Monday');
CALL newClass('dshulman@k12.somerville.ma.us','11-12:30','Monday',4);
CALL newTeam('dshulman@k12.somerville.ma.us','Monday');
CALL newStomperTeam('Jared', 'Sawyer', 'dshulman@k12.somerville.ma.us','Monday');
CALL newStomperTeam('Clara', 'Oppenheimer', 'dshulman@k12.somerville.ma.us','Monday');
CALL newClass('lhanifan@maldenps.org','10:20-12:00','Thursday',1);
CALL newTeam('lhanifan@maldenps.org','Thursday');
CALL newStomperTeam('Camila', 'Menard', 'lhanifan@maldenps.org','Thursday');
CALL newStomperTeam('Justin', 'Reyes', 'lhanifan@maldenps.org','Thursday');
CALL newClass('mnichols@maldenps.org','10:20-12:00','Thursday',1);
CALL newTeam('mnichols@maldenps.org','Thursday');
CALL newStomperTeam('Sara', 'pearce-probst', 'mnichols@maldenps.org','Thursday');
CALL newStomperTeam('Daniel', 'Weinstein', 'mnichols@maldenps.org','Thursday');
CALL newClass('lillauren0766@yahoo.com','8:00-9:00','Thursday',6);
CALL newTeam('lillauren0766@yahoo.com','Thursday');
CALL newStomperTeam('Rati', 'Srinivasan', 'lillauren0766@yahoo.com','Thursday');
CALL newStomperTeam('Ross', 'Kamen', 'lillauren0766@yahoo.com','Thursday');
CALL newClass('cwhitney@stjosephschoolmedford.com','8:00-9:00','Thursday',6);
CALL newTeam('cwhitney@stjosephschoolmedford.com','Thursday');
CALL newStomperTeam('Becca', 'Larson', 'cwhitney@stjosephschoolmedford.com','Thursday');
CALL newStomperTeam('Kevin', 'Dunn', 'cwhitney@stjosephschoolmedford.com','Thursday');
CALL newClass('acorsaro@k12.somerville.ma.us','12:00-1:00','Tuesday',4);
CALL newTeam('acorsaro@k12.somerville.ma.us','Tuesday');
CALL newStomperTeam('Erynne', 'van', 'acorsaro@k12.somerville.ma.us','Tuesday');
CALL newStomperTeam('Kanav', 'Jhunjhunwala', 'acorsaro@k12.somerville.ma.us','Tuesday');
CALL newClass('kdondero@everett.k12.ma.us','8:00-10:00','Tuesday',6);
CALL newTeam('kdondero@everett.k12.ma.us','Tuesday');
CALL newStomperTeam('Emma', 'Coltoff', 'kdondero@everett.k12.ma.us','Tuesday');
CALL newStomperTeam('Erica', 'A', 'kdondero@everett.k12.ma.us','Tuesday');
CALL newClass('jjasper@k12.somerville.ma.us','8:15-9:15','Wednesday',4);
CALL newTeam('jjasper@k12.somerville.ma.us','Wednesday');
CALL newStomperTeam('Emma', 'Cusack', 'jjasper@k12.somerville.ma.us','Wednesday');
CALL newStomperTeam('Sanya', 'Pradhan', 'jjasper@k12.somerville.ma.us','Wednesday');
CALL newClass('csnook@arlington.k12.ma.us','8:25-9:25','Wednesday',5);
CALL newTeam('csnook@arlington.k12.ma.us','Wednesday');
CALL newStomperTeam('Caitlin', 'Duffy', 'csnook@arlington.k12.ma.us','Wednesday');
CALL newStomperTeam('Amal', 'Omar', 'csnook@arlington.k12.ma.us','Wednesday');
CALL newClass('jconti@medford.k12.ma.us','9:00-11:00','Wednesday',5);
CALL newTeam('jconti@medford.k12.ma.us','Wednesday');
CALL newStomperTeam('Liren', 'Fu', 'jconti@medford.k12.ma.us','Wednesday');
CALL newStomperTeam('Eddie', 'Futterman', 'jconti@medford.k12.ma.us','Wednesday');
CALL newClass('emayer@isbos.org','1:25-3:25','Wednesday',8-Jun);
CALL newTeam('emayer@isbos.org','Wednesday');
CALL newStomperTeam('Alex', 'Klein', 'emayer@isbos.org','Wednesday');
CALL newStomperTeam('Simone', 'Draper', 'emayer@isbos.org','Wednesday');
CALL newClass('mmcdonough@maldenps.org','1:15','Wednesday',3);
CALL newTeam('mmcdonough@maldenps.org','Wednesday');
CALL newStomperTeam('Clara', 'Eshaghpour', 'mmcdonough@maldenps.org','Wednesday');
CALL newStomperTeam('Isaac.Collins@tufts.edu', '', 'mmcdonough@maldenps.org','Wednesday');


ALTER TABLE Material AUTO_INCREMENT = 1;
CALL newMaterial('Thumb Tacks and Pins',100,100,0,0);
CALL newMaterial('Rubber Bands',100,100,0,0);
CALL newMaterial('Beads and Marbles',100,100,0,0);
CALL newMaterial('Index Cards',100,100,0,0);
CALL newMaterial('Clothes Pins',100,100,0,0);
CALL newMaterial('Binder Clips',100,100,0,0);
CALL newMaterial('Paper Clips',100,100,0,0);
CALL newMaterial('Garbage Bags',100,100,0,0);
CALL newMaterial('Plastic Shopping Bags',100,100,0,0);
CALL newMaterial('Crayons/Chalk',100,100,0,0);
CALL newMaterial('Random Markers',100,100,0,0);
CALL newMaterial('Sharpies',100,100,0,0);
CALL newMaterial('Random Pens',100,100,0,0);
CALL newMaterial('Pencils/Erasers	Full',100,100,0,0);
CALL newMaterial('Balloons',100,100,0,0);
CALL newMaterial('Straws',100,100,0,0);
CALL newMaterial('Eyes',100,100,0,0);
CALL newMaterial('Stamps',100,100,0,0);
CALL newMaterial('Pipe Cleaners',100,100,0,0);
CALL newMaterial('Q-Tips/Cotton Balls',100,100,0,0);
CALL newMaterial('Tacky and Super Glue',100,100,0,0);
CALL newMaterial('Velcro',100,100,0,0);
CALL newMaterial('White Wood and Stick',100,100,0,0);
CALL newMaterial('Magnets',100,100,0,0);
CALL newMaterial('Hot Glue and Glue Guns',100,100,0,0);
CALL newMaterial('Hole Punchers',100,100,0,0);
CALL newMaterial('Razors',100,100,0,0);
CALL newMaterial('Scissors',100,100,0,0);
CALL newMaterial('Play doh',100,100,0,0);
CALL newMaterial('Wax',100,100,0,0);
CALL newMaterial('Clay',100,100,0,0);
CALL newMaterial('Water Colors',100,100,0,0);
CALL newMaterial('Emtpy Bottle',100,100,0,0);
CALL newMaterial('Brushes',100,100,0,0);
CALL newMaterial('Spray Paint',100,100,0,0);
CALL newMaterial('Poster Paint',100,100,0,0);
CALL newMaterial('Plastic Tubing',100,100,0,0);
CALL newMaterial('Filters',100,100,0,0);
CALL newMaterial('Alcohol Swabs/ Hand Warmers',100,100,0,0);
CALL newMaterial('Rules',100,100,0,0);
CALL newMaterial('Tape Measures/ Protractors',100,100,0,0);
CALL newMaterial('Magnetic Compasses',100,100,0,0);
CALL newMaterial('Stop Watch',100,100,0,0);
CALL newMaterial('Spring/Spring Scale',100,100,0,0);
CALL newMaterial('Electicity Components',100,100,0,0);
CALL newMaterial('Buzzers and Battery Packs',100,100,0,0);
CALL newMaterial('Multimeter/Wire Cutters',100,100,0,0);
CALL newMaterial('Batteries (AA)',100,100,0,0);
CALL newMaterial('Batteries (A)',100,100,0,0);
CALL newMaterial('Batteries(C,D)',100,100,0,0);
CALL newMaterial('Solar Kit',100,100,0,0);
CALL newMaterial('Ties and Fasteners',100,100,0,0);
CALL newMaterial('Solar Plate Materials',100,100,0,0);
CALL newMaterial('Sound Recording/ Music Wires',100,100,0,0);
CALL newMaterial('Flashlights',100,100,0,0);
CALL newMaterial('Marshmellow Bags',100,100,0,0);
CALL newMaterial('Spaghetti Boxes',100,100,0,0);
CALL newMaterial('Plastic Objects',100,100,0,0);
CALL newMaterial('Utensils, Wax Paper',100,100,0,0);
CALL newMaterial('Paper and Cardboard',100,100,0,0);
CALL newMaterial('Pantry Dry Goods',100,100,0,0);
CALL newMaterial('Cloth',100,100,0,0);
CALL newMaterial('Coffee Filters, Paper Plates',100,100,0,0);
CALL newMaterial('Cups',100,100,0,0);
CALL newMaterial('Yarn, String, Rope, Feathers',100,100,0,0);
CALL newMaterial('Felt',100,100,0,0);
CALL newMaterial('Tape',100,100,0,0);
CALL newMaterial('Paper',100,100,0,0);
CALL newMaterial('Popsicle Stics',100,100,0,0);
CALL newMaterial('Styrofoam/Bubble Wrap',100,100,0,0);
CALL newMaterial('Figurines',100,100,0,0);
CALL newMaterial('Ping Pong balls',100,100,0,0);
CALL newMaterial('Plastic Balls',100,100,0,0);
CALL newMaterial('Large Wood Pieces',100,100,0,0);
CALL newMaterial('PVC Pipe',100,100,0,0);
CALL newMaterial('Egg Cartons',100,100,0,0);
CALL newMaterial('Plastic Tubing',100,100,0,0);
CALL newMaterial('Pipe Cutters',100,100,0,0);
CALL newMaterial('Spigots',100,100,0,0);
CALL newMaterial('Elbow Joints',100,100,0,0);
CALL newMaterial('Plastic Containers',100,100,0,0);
CALL newMaterial('Potting Soil',100,100,0,0);
CALL newMaterial('Sand',100,100,0,0);
CALL newMaterial('Snap Circuit Pieces',100,100,0,0);
CALL newMaterial('Styrofoam Packing Peanuts',100,100,0,0);
CALL newMaterial('Paper Bags',100,100,0,0);
CALL newMaterial('Squishy Circuits',3,100,0,1);
CALL newMaterial('Spaghetti Towers',1,100,0,1);
CALL newMaterial('Sturdy Structures',17,100,0,1);
CALL newMaterial('Simple Machines',8,100,0,1);
